### ISSUE TITLE
`darglint` incuded in `.pre-commit-config.yaml` when ansersing `no`

### ISSUE THREAD

**Issue by Victorlouisdg** [tlpss/research-template#6]
Even if you say `no` to the `darglint` option during the setup prompts, this is still included in `.pre-commit-config.yaml`:
```
-   repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
    - id: darglint
```
